spring:
  messages:
    basename: messages
    encoding: UTF-8
  mvc:
    locale-resolver: accept-header
  application:
    name: reto-tecenico
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nodos_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: reto
        hbm2ddl:
          create_namespaces: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          meta:
            client-id: ${META_CLIENT_ID}
            client-secret: ${META_CLIENT_SECRET}
            scope: public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          meta:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v18.0/me
            user-name-attribute: id

server:
  port: ${PORT:${SERVER_PORT:8081}}
  forward-headers-strategy: framework
  tomcat:
    threads:
      max: 20

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET:default_secret_key_please_change}

backend:
  url: ${BACKEND_URL:http://localhost:8081/auth

resend:
  token: ${RESEND_API_KEY:dummy_key_for_tests}
  email:
    from: ${RESEND_EMAIL_FROM:onboarding@resend.dev}
    to: ${RESEND_EMAIL_TO:destino@dominio.com}

crypto:
  secret-key: ${CRYPTO_SECRET_KEY:ILluF20Aavb5J6XZ/qw67TSAQxkCPoi3IWQs1fI2sYA=}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173/}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}
